Repository stellargraph/stellargraph, pull requests merged in 2019-12, with the labels that each got.

#521 Feature/clustergcn
  CHANGELOG.md
  README.md
  demos/README.md
  demos/node-classification/README.md
  demos/node-classification/cluster-gcn/cluster-gcn-node-classification.ipynb
  docs/api.txt
  stellargraph/__init__.py
  stellargraph/layer/__init__.py
  stellargraph/layer/cluster_gcn.py
  stellargraph/mapper/__init__.py
  stellargraph/mapper/mini_batch_node_generators.py
  tests/layer/test_cluster_gcn.py
  tests/mapper/test_cluster_gcn_node_mapper.py
Labels: ml

#549 Changed .node[ to .nodes[ in cluster-GCN demo notebook
  demos/node-classification/cluster-gcn/cluster-gcn-node-classification.ipynb
Labels: ml

#501 Replace inheritance of NetworkX by encapsulation
  CHANGELOG.md
  demos/embeddings/stellargraph-attri2vec-citeseer.ipynb
  demos/interpretability/gat/node-link-importance-demo-gat.ipynb
  demos/node-classification/graphsage/directed-graphsage-on-cora-example.ipynb
  scripts/test_demos.py
  stellargraph/core/graph.py
  stellargraph/core/graph_networkx.py
  stellargraph/data/converter.py
  stellargraph/data/explorer.py
  stellargraph/data/node_splitter.py
  stellargraph/data/unsupervised_sampler.py
  stellargraph/mapper/full_batch_generators.py
  stellargraph/mapper/mini_batch_node_generators.py
  stellargraph/mapper/sampled_link_generators.py
  stellargraph/mapper/sampled_node_generators.py
  tests/core/test_stellargraph.py
  tests/core/test_types.py
  tests/core/test_utils.py
  tests/data/test_biased_random_walker.py
  tests/data/test_breadth_first_walker.py
  tests/data/test_converters.py
  tests/data/test_heterogeneous_breadth_first_walker.py
  tests/mapper/test_directed_node_generator.py
  tests/mapper/test_link_mappers.py
  tests/mapper/test_node_mappers.py
Labels: ml

#523 Added script to format and remove warnings from demo notebooks
  scripts/README.md
  scripts/format_notebooks.py
  scripts/requirements.txt
  scripts/test_demos.py
Labels: ml

#564 Removed unused dense attention calculation in GraphAttentionSparse class
  stellargraph/layer/graph_attention.py
Labels: bug, ml

#569 fixed unit test for symmetric normalized laplacian
  tests/core/test_utils.py
Labels: bug

#518 Update to support TensorFlow 2 API
  CHANGELOG.md
  demos/interpretability/gat/node-link-importance-demo-gat.ipynb
  demos/interpretability/gcn/hateful-twitters-interpretability.ipynb
  demos/interpretability/gcn/node-link-importance-demo-gcn-sparse.ipynb
  demos/interpretability/gcn/node-link-importance-demo-gcn.ipynb
  demos/node-classification/ppnp/ppnp-cora-node-classification-example.ipynb
  requirements.txt
  setup.py
  stellargraph/layer/graph_attention.py
  stellargraph/layer/preprocessing_layer.py
  stellargraph/mapper/full_batch_generators.py
  stellargraph/mapper/sequences.py
  stellargraph/utils/calibration.py
  stellargraph/utils/saliency_maps/integrated_gradients.py
  stellargraph/utils/saliency_maps/saliency.py
  stellargraph/utils/saliency_maps/saliency_gat.py
  tests/layer/test_appnp.py
  tests/layer/test_link_inference.py
  tests/layer/test_misc.py
  tests/layer/test_rgcn.py
  tests/utils/test_ensemble.py
  tests/utils/test_saliency_maps_gat.py
  tests/utils/test_saliency_maps_gcn.py
Labels: help wanted, ml
