Repository stellargraph/stellargraph, pull requests merged in 2019-04, with the labels that each got.

#362 Removed label from features for pubmed dataset.
  demos/ensembles/ensemble-node-classification-example.ipynb
Labels: bug, ml

#324 added Citing info to README
  README.md
Labels: ml

#361 SGC Implementation
  README.md
  demos/node-classification/README.md
  demos/node-classification/sgc/sgc-node-classification-example.ipynb
  stellargraph/core/utils.py
  stellargraph/mapper/node_mappers.py
  tests/core/test_utils.py
Labels: enhancement, ml

#372 Inductive GraphSAGE demo
  demos/node-classification/graphsage/README.md
  demos/node-classification/graphsage/graphsage-pubmed-inductive-node-classification-example.ipynb
Labels: ml

#338 Updated generators to pass graph schema to walkers
  stellargraph/mapper/link_mappers.py
  stellargraph/mapper/node_mappers.py
  tests/mapper/test_node_mappers.py
Labels: ml
