Repository stellargraph/stellargraph, pull requests merged in 2020-01, with the labels that each got.

#543 Feature/fullbatch linkgenerator
  demos/ensembles/ensemble-node-classification-example.ipynb
  demos/interpretability/gat/node-link-importance-demo-gat.ipynb
  demos/interpretability/gcn/hateful-twitters-interpretability.ipynb
  demos/interpretability/gcn/node-link-importance-demo-gcn-sparse.ipynb
  demos/interpretability/gcn/node-link-importance-demo-gcn.ipynb
  demos/link-prediction/gcn/cora-gcn-links-example.ipynb
  demos/node-classification/cluster-gcn/cluster-gcn-node-classification.ipynb
  demos/node-classification/gat/gat-cora-example.py
  demos/node-classification/gat/gat-cora-node-classification-example.ipynb
  demos/node-classification/gcn/gcn-cora-example.py
  demos/node-classification/gcn/gcn-cora-node-classification-example.ipynb
  demos/node-classification/ppnp/ppnp-cora-node-classification-example.ipynb
  demos/node-classification/sgc/sgc-node-classification-example.ipynb
  demos/use-cases/hateful-twitters.ipynb
  docs/api.txt
  docs/conf.py
  docs/quickstart.txt
  scripts/README.md
  scripts/format_notebooks.py
  stellargraph/core/graph_networkx.py
  stellargraph/layer/appnp.py
  stellargraph/layer/gcn.py
  stellargraph/layer/graph_attention.py
  stellargraph/layer/link_inference.py
  stellargraph/layer/ppnp.py
  stellargraph/mapper/full_batch_generators.py
  stellargraph/mapper/sequences.py
  stellargraph/utils/ensemble.py
  stellargraph/utils/saliency_maps/saliency.py
  stellargraph/utils/saliency_maps/saliency_gat.py
  tests/core/test_stellargraph.py
  tests/layer/test_appnp.py
  tests/layer/test_gcn.py
  tests/layer/test_graph_attention.py
  tests/layer/test_graphsage.py
  tests/layer/test_link_inference.py
  tests/layer/test_ppnp.py
  tests/mapper/test_full_batch_generators.py
  tests/utils/test_ensemble.py
  tests/utils/test_saliency_maps_gat.py
  tests/utils/test_saliency_maps_gcn.py
Labels: sg-library

#733 Add cell timeout option and correct documentation for scripts/format_notebooks
  scripts/README.md
  scripts/format_notebooks.py
Labels: doc, sg-library

#746 clear cell warnings after executing notebooks in format_notebooks
  scripts/format_notebooks.py
Labels: bug, sg-library
