Repository stellargraph/stellargraph, pull requests merged in 2020-04, with the labels that each got.

#1260 Fix bug using METIS for in ClusterGCN demo
  demos/node-classification/cluster-gcn/cluster-gcn-node-classification.ipynb
Labels: bug, sg-library

#1210 Feature/1044 sortpooling layer
  stellargraph/layer/__init__.py
  stellargraph/layer/sort_pooling.py
  tests/layer/test_sort_pooling.py
Labels: enhancement, sg-library

#1085 Feature/gcn lstm
  .buildkite/pipeline.yml
  .buildkite/steps/test-demo-notebooks.sh
  demos/spatio-temporal/gcn-lstm-LA.ipynb
  stellargraph/core/utils.py
  stellargraph/datasets/datasets.py
  stellargraph/layer/__init__.py
  stellargraph/layer/gcn_lstm.py
Labels: sg-library

#1311 Fixed issue no. from 9999 to 1303 for METR-LA class
  stellargraph/datasets/datasets.py
Labels: sg-library

#1317 Release 1.0.0rc1
  demos/basics/loading-networkx.ipynb
  demos/basics/loading-pandas.ipynb
  demos/basics/loading-saving-neo4j.ipynb
  demos/calibration/calibration-pubmed-link-prediction.ipynb
  demos/calibration/calibration-pubmed-node-classification.ipynb
  demos/community_detection/attacks_clustering_analysis.ipynb
  demos/connector/neo4j/directed-graphsage-on-cora-neo4j-example.ipynb
  demos/connector/neo4j/load-cora-into-neo4j.ipynb
  demos/connector/neo4j/undirected-graphsage-on-cora-neo4j-example.ipynb
  demos/embeddings/deep-graph-infomax-cora.ipynb
  demos/embeddings/embeddings-unsupervised-graphsage-cora.ipynb
  demos/embeddings/graphwave-barbell.ipynb
  demos/embeddings/stellargraph-attri2vec-citeseer.ipynb
  demos/embeddings/stellargraph-metapath2vec.ipynb
  demos/embeddings/stellargraph-node2vec.ipynb
  demos/embeddings/watch-your-step-cora-demo.ipynb
  demos/ensembles/ensemble-link-prediction-example.ipynb
  demos/ensembles/ensemble-node-classification-example.ipynb
  demos/graph-classification/supervised-graph-classification.ipynb
  demos/interpretability/gat/node-link-importance-demo-gat.ipynb
  demos/interpretability/gcn/hateful-twitters-interpretability.ipynb
  demos/interpretability/gcn/node-link-importance-demo-gcn-sparse.ipynb
  demos/interpretability/gcn/node-link-importance-demo-gcn.ipynb
  demos/link-prediction/attri2vec/stellargraph-attri2vec-DBLP.ipynb
  demos/link-prediction/gcn/cora-gcn-links-example.ipynb
  demos/link-prediction/graphsage/cora-links-example.ipynb
  demos/link-prediction/hinsage/movielens-recommender.ipynb
  demos/link-prediction/knowledge-graphs/complex.ipynb
  demos/link-prediction/knowledge-graphs/distmult.ipynb
  demos/link-prediction/random-walks/cora-lp-demo.ipynb
  demos/link-prediction/random-walks/ctdne-link-prediction.ipynb
  demos/node-classification/attri2vec/attri2vec-citeseer-node-classification-example.ipynb
  demos/node-classification/cluster-gcn/cluster-gcn-node-classification.ipynb
  demos/node-classification/gat/gat-cora-node-classification-example.ipynb
  demos/node-classification/gcn/gcn-cora-node-classification-example.ipynb
  demos/node-classification/graphsage/directed-graphsage-on-cora-example.ipynb
  demos/node-classification/graphsage/graphsage-cora-node-classification-example.ipynb
  demos/node-classification/graphsage/graphsage-pubmed-inductive-node-classification-example.ipynb
  demos/node-classification/node2vec/stellargraph-node2vec-node-classification.ipynb
  demos/node-classification/node2vec/stellargraph-node2vec-weighted-random-walks.ipynb
  demos/node-classification/ppnp/ppnp-cora-node-classification-example.ipynb
  demos/node-classification/rgcn/rgcn-aifb-node-classification-example.ipynb
  demos/node-classification/sgc/sgc-node-classification-example.ipynb
  demos/spatio-temporal/gcn-lstm-LA.ipynb
  demos/use-cases/hateful-twitters.ipynb
  meta.yaml
  stellargraph/version.py
Labels: sg-library

#1309 Return figure in plot_history
  stellargraph/utils/history.py
Labels: external

#1405 Update calibration demo notebook
  demos/calibration/calibration-pubmed-node-classification.ipynb
Labels: external

#1412 Bugfix/1085_gcn_lstm_dogfooding
  demos/spatio-temporal/gcn-lstm-LA.ipynb
  stellargraph/layer/gcn_lstm.py
Labels: sg-library
